---
language: python
python: "3.9"

dist: bionic
os: linux

services:
  - docker

env:
  global:
    - ROLLE_NAME: nvim_build

install:
  - pip install ansible docker-py molecule[docker] molecule[lint]

before_script:
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\nhost_key_checking = False' >ansible.cfg

script:
  - molecule test
  # - ansible-playbook tests/test.yml -i tests/inventory --connection=local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
