---
language: python
python: "3.9"

dist: ubuntu
os: linux

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible molecule[docker] yamllint ansible-lint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory
  # - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
