---
# extras task

- name: install or update lua lsp mac
  shell: |
    git pull
    git submodule update --init --recursive
    cd 3rd/luamake
    ninja -f ninja/macos.ninja
    cd ../..
    ./3rd/luamake/luamake rebuild
  args:
    chdir: "{{ gits_dir }}/lua-language-server"
    executable: "{{ exe_shell }}"
  when: ansible_system == 'Darwin' and lsp_lua_mac
  register: maclsp
  changed_when: maclsp.rc == '0'

- name: install or update lua lsp lx
  shell: |
    git pull
    git submodule update --init --recursive
    cd 3rd/luamake
    ninja -f ninja/linux.ninja
    cd ../..
    ./3rd/luamake/luamake rebuild
  args:
    chdir: "{{ gits_dir }}/lua-language-server"
    executable: "{{ exe_shell }}"
  when: >
    ansible_system == 'Linux' and
    ansible_architecture != "armv7l" and lsp_lua_lx
  register: lxlsp
  changed_when: lxlsp.rc == '0'
...
