---
# extras task

- name: clone or update sumneko lua repo ssh
  ansible.builtin.git:
    repo: git@github.com:sumneko/lua-language-server.git
    dest: "{{ gits_dir }}/lua-language-server"
    version: HEAD
    accept_hostkey: yes
    track_submodules: yes
    force: yes
    clone: yes
    update: yes
    key_file: "{{ git_key }}"
  when: git_method == 'ssh'
  tags:
    - molecule-idempotence-notest

- name: clone or update sumneko lua repo https
  ansible.builtin.git:
    repo: https://github.com/sumneko/lua-language-server.git
    dest: "{{ gits_dir }}/lua-language-server"
    version: HEAD
    track_submodules: yes
    clone: yes
    force: yes
    update: yes
  when: git_method != 'ssh'
  tags:
    - molecule-idempotence-notest

- name: install or update lua lsp mac
  shell: |
    cd 3rd/luamake
    ninja -f ninja/macos.ninja
    cd ../..
    ./3rd/luamake/luamake rebuild
  args:
    chdir: "{{ gits_dir }}/lua-language-server"
    executable: "{{ exe_shell }}"
  when: ansible_system == 'Darwin'
  register: maclsp
  changed_when: maclsp.rc == '0'

- name: install or update lua lsp lx
  shell: |
    cd 3rd/luamake
    ninja -f ninja/linux.ninja
    cd ../..
    ./3rd/luamake/luamake rebuild
  args:
    chdir: "{{ gits_dir }}/lua-language-server"
    executable: "{{ exe_shell }}"
  when: >
    ansible_system == 'Linux' and
    ansible_architecture != 'armv7l'
  register: lxlsp
  changed_when: lxlsp.rc == '0'
...
