---
- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: no
    mode: 0755
  with_items: "{{ nv_dirs }}"
  when: nv_dirs_mk

- include_tasks: tasks/packs.yaml

- name: load ssh formatted git urls
  include_vars: vars/git_ssh.yml
  when: git_method == 'ssh'

- name: load https formatted git urls
  include_vars: vars/git_https.yml
  when: git_method != 'ssh'

- name: clone user config
  git:
    repo: "{{ nvrc_url }}"
    dest: "{{ nvim_dir }}"
    version: HEAD
    accept_hostkey: yes
    clone: yes
    force: no
    update: yes
    key_file: "{{ git_key }}"

- name: clone source repo for build
  git:
    repo: "{{ nvim_url }}"
    dest: "{{ nvim_build_dir }}"
    version: HEAD
    accept_hostkey: yes
    clone: yes
    update: yes
    key_file: "{{ git_key }}"

- name: clone extra repos ssh
  git:
    repo: "{{ 'git@github.com:%s.git' | format(item.repo) }}"
    # repo: "{{  item }}"
    dest: "{{ gits_dir }}/{{ item.name }}"
    version: HEAD
    accept_hostkey: yes
    clone: yes
    update: yes
    key_file: "{{ git_key }}"
  with_items: "{{ gits }}"
  when: git_method == 'ssh' and gits is iterable

- name: clone extra repos https
  git:
    repo: "{{ 'https://github.com/%s.git' | format(item.repo) }}"
    dest: "{{ gits_dir }}/{{ item.name }}"
    version: HEAD
    clone: yes
    update: yes
  with_items: "{{ gits }}"
  when: git_method != 'ssh' and gits is iterable

- include_tasks: tasks/extras.yaml

- name: clean up artifacts from prior builds
  community.general.make:
    chdir: "{{ nvim_build_dir }}"
    target: distclean
    make: "{{ exe_make }}"
  when: build_it
  tags:
    - molecule-idempotence-notest

- name: build release target
  community.general.make:
    chdir: "{{ nvim_build_dir }}"
    params:
      CMAKE_BUILD_TYPE: Release
      CMAKE_INSTALL_PREFIX: "{{ ansible_env.HOME }}/.local"
    target: install
    make: "{{ exe_make }}"
  when: build_it
  tags:
    - molecule-idempotence-notest
...
