---
- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: no
    mode: 0750
  with_items: "{{ nv_dirs }}"
  when: nv_dirs_mk

- include_tasks: tasks/packs.yaml

- name: clone user config
  git:
    repo: "{{ nvrc_url }}"
    dest: "{{ nvim_dir }}"
    version: master
    accept_hostkey: yes
    clone: yes
    force: no
    update: yes
    key_file: "{{ git_key }}"

- name: clone source repo for build
  git:
    repo: "{{ nvim_url }}"
    dest: "{{ gits_dir }}/{{ nvim_source }}"
    version: master
    accept_hostkey: yes
    clone: yes
    update: yes
    key_file: "{{ git_key }}"

- name: clone extra repos ssh
  git:
    repo: "{{ item.url }}"
    dest: "{{ gits_dir }}/{{ item.name }}"
    version: master
    accept_hostkey: yes
    clone: yes
    update: yes
    key_file: "{{ git_key }}"
  with_items: "{{ gits }}"

- include_tasks: tasks/extras.yaml

- name: clean up artifacts from prior builds
  community.general.make:
    chdir: "{{ nvim_build_dir }}"
    target: distclean
    make: "{{ exe_make }}"
  when: build_it

- name: build release target
  community.general.make:
    chdir: "{{ nvim_build_dir }}"
    params:
      CMAKE_BUILD_TYPE: Release
      CMAKE_INSTALL_PREFIX: ~/.local
    target: install
    make: "{{ exe_make }}"
  when: build_it
...
