---
- name: Converge
  hosts: all
  vars:
    build_it: yes
    nvrc_repo: klooj/nvimrc-lua
    nv_dirs_mk: yes
    lsp_lua_lx: yes
    exe_shell: /usr/bin/zsh
    exe_make: /usr/bin/make

    install_apts: yes

  tasks:
    - name: update apt
      apt:
        update_cache: true
        cache_valid_time: 86400
      when: ansible_os_family == 'Debian'

    - include_role:
        name: nvim_build
